### PR TITLE
Update 7

### PR DESCRIPTION
**Pull request by hellais**

### CODE REVIEW

**Review by anadahz — DISMISSED** [review]
Lines 75 - 81 are not needed (this happened already on the 6th update) and may even cause an issue on upgrade.

**Comment by hellais** [comment]
> Lines 75 - 81 are not needed (this happened already on the 6th update) and may even cause an issue on upgrade.

Actually it will not happen if somebody had already updated to the latest version after December 7, but before Feb 16th (see: https://github.com/OpenObservatory/lepidopter-update/commit/6dc783555ddbc88f5f2d02df030447326b74759b)

**Comment by anadahz** [comment]
@hellais indeed you are correct.
Let's merge this PR.

**Comment by hellais** [comment]
🎉

**Pull request merged**
